# Generated by Django 6.0 on 2025-12-12 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_cancha_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorasNoDisponibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.cancha')),
            ],
            options={
                'verbose_name': 'Hora no disponible',
                'verbose_name_plural': 'Horas no disponibles',
                'ordering': ('-fecha', 'cancha'),
            },
        ),
    ]
