# Generated by Django 5.2.5 on 2025-12-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_categoria_remove_cancha_tipo_cancha_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='canchas/'),
        ),
    ]
