# Generated by Django 6.0 on 2025-12-12 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_horasnodisponibles'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaBloqueado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=200, null=True)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.cancha')),
            ],
            options={
                'verbose_name': 'Día bloqueado',
                'verbose_name_plural': 'Días bloqueados',
                'unique_together': {('cancha', 'fecha')},
            },
        ),
    ]
