# Generated by Django 6.0 on 2025-12-12 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_diabloqueado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fechasnodisponibles',
            options={},
        ),
    ]
