# Generated by Django 6.0 on 2025-12-12 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_alter_fechasnodisponibles_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fechasnodisponibles',
            options={'verbose_name': 'Fecha no disponible', 'verbose_name_plural': 'Fechas no disponibles'},
        ),
        migrations.DeleteModel(
            name='DiaBloqueado',
        ),
    ]
